apiVersion: v1
kind: Service
metadata:
  name: nyrvex
  namespace: web-nyrvex
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nyrvex
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
